make use of makepkg utils

diff --git a/build-aur-pkg b/build-aur-pkg
--- a/build-aur-pkg
+++ b/build-aur-pkg
@@ -13,16 +13,13 @@
 ## part of the package-base will be built - even if the user
 ## does not want this.
 
-readonly ROOTDIR="$HOME"
-
-readonly PKGDIR="aur-src"
-readonly PKGPATH="$ROOTDIR/$PKGDIR"
-readonly DB="viesspkg"
+## Default options
+pkgdir="aur-src"
+dbname="viesspkg"
 
 parse_srcinfo() {
     ## print out pkgnames with version info
-    local file
-    local pkgver
+    local file pkgver
 
     file="$1/.SRCINFO"
     pkgver="$(grep pkgver "$file" | cut -d' ' -f3)"
@@ -35,34 +32,62 @@ uniq_unsorted() {
     cat -n "$1" | sort -uk2 | sort -nk2 | cut -f2-
 }
 
+source /usr/share/makepkg/util/message.sh
+source /usr/share/makepkg/util/parseopts.sh
+source /usr/share/makepkg/util/util.sh
+
+## Handle Options
+readonly OPT_SHORT='d:hn:'
+readonly OPT_LONG=('dir:' 'help' 'name:')
+
+usage() {
+    plain "Usage: %s [--dir PKGDIR] [--name DBNAME] [--help]" "build-aur-pkg"
+}
+
+if ! parseopts "$OPT_SHORT" "${OPT_LONG[@]}" -- "$@"; then
+    exit 1
+fi
+set -- "${OPTRET[@]}"
+
+while true; do
+    case "$1" in
+        -d|--dir) shift; pkgdir="$1"; ;;
+        -h|--help) usage; exit 0; ;;
+        -n|--name) shift; dbname="$1"; ;;
+        --) shift; break; ;;
+    esac
+    shift
+done
+
 tmp="$(mktemp -d)"
 if [ ! -d "$tmp" ]; then
-    echo "Unable to create temp directory!" >&2
+    error "Unable to create temp directory!"
     exit 2
 fi
 trap 'rm -rf $tmp' EXIT
 
-if [ ! -d "$PKGPATH" ]; then
-    echo "Must be run relative to $PKGPATH" >&2
+readonly pkgpath="$(canonicalize_path "$pkgdir")"
+if [ ! -d "$pkgpath" ]; then
+    error "\`$pkgpath' does not exist!"
     exit 1
 fi
 
 # get all currently fetched aur pkgs
-find "$PKGPATH" -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | sort > "$tmp/pkgdirs"
+find "$pkgpath" -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | sort > "$tmp/pkgdirs"
 
 pushd "$tmp"
 
 # retrieve path to local repo
-aur repo -S -d "$DB" --list --status-file=db | sort > db_info
+aur repo -S -d "$dbname" --list --status-file=db | sort > db_info
 
 { IFS= read -r db_name
   IFS= read -r db_root
 } < "$tmp/db"
 
 if [[ -w $db_root/$db_name.db ]]; then
-    echo "Using [$db_name] repository" >&2
+    msg "Using [$db_name] repository"
 else
-    echo "Error: $db_root/$db_name.db: permission denied" >&2
+    error "$db_root/$db_name.db: permission denied"
     exit 1
 fi
 
@@ -71,35 +96,35 @@ aur vercmp --quiet < db_info > aurupdate
 cut -f1 aurupdate > aurupdate.pkgname
 
 # parse srcinfo (for pkgnames)
-while read -r pkgdir; do
-    echo "=> Checking pkgbase \`$pkgdir'"
-    echo "==> Parsing .SRCINFO"
-    parse_srcinfo "$PKGPATH/$pkgdir" > "$pkgdir.depends"
-    cut -f1 "$pkgdir.depends" > "$pkgdir"
-    echo "==> Checking if new or updated"
-    cut -f1 db_info | comm -13 - "$pkgdir" > "$pkgdir.new"
-    comm -12 aurupdate.pkgname "$pkgdir" > "$pkgdir.update"
+while read -r pkg; do
+    msg "Checking pkgbase \`$pkg'"
+    msg2 "Parsing .SRCINFO"
+    parse_srcinfo "$pkgpath/$pkg" > "$pkg.depends"
+    cut -f1 "$pkg.depends" > "$pkg"
+    msg2 "Checking if new or updated"
+    cut -f1 db_info | comm -13 - "$pkg" > "$pkg.new"
+    comm -12 aurupdate.pkgname "$pkg" > "$pkg.update"
 
-    if [ -s "$pkgdir.new" ] || [ -s "$pkgdir.update" ]; then
-        echo "==> Added \`$pkgdir' to build queue"
-        if ! aur depends -b "$pkgdir" 2> /dev/null >> pkgord; then
+    if [ -s "$pkg.new" ] || [ -s "$pkg.update" ]; then
+        msg2 "Added \`$pkg' to build queue"
+        if ! aur depends -b "$pkg" 2> /dev/null >> pkgord; then
             # pkgdir is a group of pkgs
-            echo "$pkgdir" >> pkgord
+            echo "$pkg" >> pkgord
         fi
     else
-        echo "==> Already latest, skipping..."
+        msg2 "Already latest, skipping..."
     fi
 done < pkgdirs
 
 if [ -s pkgord ]; then
-    uniq_unsorted pkgord | sed "s|^\(.*\)$|$PKGDIR\/\1|" > queue
+    uniq_unsorted pkgord | sed "s|^\(.*\)$|$pkgdir\/\1|" > queue
 fi
 
 popd
 
 if [ -s "$tmp/queue" ]; then
-    xargs -a "$tmp/queue" -n1 -P1 -I{} echo "=> Building {}"
-    aur build -a "$tmp/queue" -c -d "$DB" -s
+    xargs -a "$tmp/queue" -n1 -P1 -I{} msg "Building {}"
+    aur build -a "$tmp/queue" -c -d "$dbname" -s
 else
-    echo "Nothing to build"
+    msg "Nothing to build"
 fi
diff --git a/fetch-aur-pkg b/fetch-aur-pkg
--- a/fetch-aur-pkg
+++ b/fetch-aur-pkg
@@ -15,45 +15,71 @@
 ##  should be of the form `<filename+extenstion>.patch`, e.g.
 ##  `PKGBUILD.patch`. Patches are applied on each call of this script.
 
-readonly ROOTDIR="$HOME"
+## Default options
+pkglist="aur-pkgs-list"
+pkgdir="aur-src"
+patchdir="aur-src-patches"
 
-readonly PKGLIST="$ROOTDIR/aur-pkgs-list"
-readonly PKGDIR="$ROOTDIR/aur-src"
-readonly PATCHDIR="$ROOTDIR/aur-src-patches"
+source /usr/share/makepkg/util/message.sh
+source /usr/share/makepkg/util/parseopts.sh
 
-if [ ! -s "$PKGLIST" ]; then
-	echo "Can't find pkg list, create \`${PKGLIST##*/}\` first before running!" >&2
+## Handle Options
+readonly OPT_SHORT='d:hl:p:'
+readonly OPT_LONG=('dir:' 'help' 'list:' 'pdir:')
+
+usage() {
+    plain "Usage: %s [--dir PKGDIR] [--list PKGLIST] [--pdir PATCHDIR] [--help]" "fetch-aur-pkg"
+}
+
+if ! parseopts "$OPT_SHORT" "${OPT_LONG[@]}" -- "$@"; then
+    exit 1
+fi
+set -- "${OPTRET[@]}"
+
+while true; do
+    case "$1" in
+        -d|--dir) shift; pkgdir="$1"; ;;
+        -h|--help) usage; exit 0; ;;
+        -l|--list) shift; pkglist="$1"; ;;
+        -p|--pdir) shift; patchdir="$1"; ;;
+        --) shift; break; ;;
+    esac
+    shift
+done
+
+if [ ! -s "$pkglist" ]; then
+    error "Can't find pkg list, create \`${pkglist##*/}\` first before running!"
 	exit 1
 else
 	# make sure pkg source dir exists
-	mkdir -p "$PKGDIR"
+	[ -d "$pkgdir" ] || mkdir -p "$pkgdir"
 
 	tmp=$(mktemp -d)
 	trap 'rm -rf $tmp' EXIT
 
-	echo -n "Determining AUR dependencies... "
+	msg "Determining AUR dependencies... "
 	while read -r pkg; do
 		aur depends -b "$pkg" >> "$tmp/depends"
-	done < "$PKGLIST"
-	echo "done"
+	done < "$pkglist"
 	
 	sort -u "$tmp/depends" > "$tmp/pkglist"
 
-	pushd "$PKGDIR"
-	echo "Fetching packages and their AUR dependencies... "
+	pushd "$pkgdir"
+	msg "Fetching packages and their AUR dependencies... "
 	# we want to always reset (so that patch apply cleanly)
 	find . -mindepth 1 -maxdepth 1 -type d -exec git -C {} reset -q --hard master \;
 	xargs -a "$tmp/pkglist" -n1 -P4 aur fetch -g
-    echo "Pruning defunted repos... "
+    msg "Pruning defunted repos... "
+    # shellcheck disable=SC2046
     find . -mindepth 1 -maxdepth 1 -type d \( $(printf -- "-path */%s -o " $(cat "$tmp/pkglist")) -false \) -prune -o -type d -printf "%P\n" > "$tmp/prune"
     xargs -a "$tmp/prune" -n1 -P1 rm -rf
 	popd
 
-	echo "Checking for patches... "
+	msg "Checking for patches... "
 	while read -r pkg; do
-		if [ -d "${PATCHDIR}/${pkg}" ]; then
-			echo "   found patch, patching $pkg"
-			find "${PATCHDIR}/${pkg}" -iname '*.patch' -exec patch -d "$PKGDIR/$pkg" -p1 -i {} \;
+		if [ -d "${patchdir}/${pkg}" ]; then
+			msg2 "found patch, patching $pkg"
+			find "${patchdir}/${pkg}" -iname '*.patch' -exec patch -d "$pkgdir/$pkg" -p1 -i {} \;
 		fi
-	done < "$PKGLIST"
+	done < "$pkglist"
 fi
