add further support/features
- build now handles package-bases
- fetch prunes defunct repos

diff --git a/build-aur-pkg b/build-aur-pkg
--- a/build-aur-pkg
+++ b/build-aur-pkg
@@ -1,11 +1,44 @@
 #!/usr/bin/env bash
 
-# this script will build AUR packeges previously fetched
+## this script will build AUR packages which have been previously
+## cloned. The script *does not* read any pkglist, or other user
+## input. It builds all cloned packages located in {PKGDIR}.
 
-readonly PKGDIR="aur-src"
+## The script expects all package AUR dependencies to be already
+## resolved, any missing repos will lead to failure.
+
+## Some packages are part of package-bases which are a type of
+## meta package. This script has rudimentry way of detecting
+## and building. Because of limitations with makepkg, all packages
+## part of the package-base will be built - even if the user
+## does not want this.
+
+readonly ROOTDIR="$HOME"
+
+readonly PKGDIR="$ROOTDIR/aur-src"
 readonly DB="viesspkg"
 
-tmp=$(mktemp -d)
+parse_srcinfo() {
+    ## print out pkgnames with version info
+    local file
+    local pkgver
+
+    file="$1/.SRCINFO"
+    pkgver="$(grep pkgver "$file" | cut -d' ' -f3)"
+
+    grep pkgname "$file" | cut -d' ' -f3 | sort | sed "s|\$| $pkgver|"
+}
+
+uniq_unsorted() {
+    # remove all duplicate lines *without* changing the general order of lines
+    cat -n "$1" | sort -uk2 | sort -nk2 | cut -f2-
+}
+
+tmp="$(mktemp -d)"
+if [ ! -d "$tmp" ]; then
+    echo "Unable to create temp directory!" >&2
+    exit 2
+fi
 trap 'rm -rf $tmp' EXIT
 
 if [ ! -d "$PKGDIR" ]; then
@@ -14,15 +47,12 @@ if [ ! -d "$PKGDIR" ]; then
 fi
 
 # get all currently fetched aur pkgs
-find "$PKGDIR" -mindepth 1 -maxdepth 1 -type d -print | sort > "$tmp/pkgdirs"
+find "$PKGDIR" -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | sort > "$tmp/pkgdirs"
 
 pushd "$tmp"
 
-# parse pkgdirs into pkgnames
-xargs -a pkgdirs -n1 -P1 -I{} basename {} > pkgs
-
 # retrieve path to local repo
-aur repo -d "$DB" --list --status-file=db > db_info
+aur repo -S -d "$DB" --list --status-file=db | sort > db_info
 
 { IFS= read -r db_name
   IFS= read -r db_root
@@ -35,27 +65,37 @@ else
     exit 1
 fi
 
-# get new AUR pkgs that *are not* in the package repo
-cut -f1 db_info | comm -13 - pkgs > newpkgs
-
 # collect all pkgs that have been updated (in AUR!)
-aur vercmp --quiet < db_info | cat - newpkgs > pkgupdate
+aur vercmp --quiet < db_info > aurupdate
+cut -f1 aurupdate > aurupdate.pkgname
 
-# we need to correctly order packages, with dependencies
-# first. XXX this is dirty... and breaks the above check...
-while read -r line; do
-    aur depends -n "$line" >> pkgord
-done < pkgupdate
+# parse srcinfo (for pkgnames)
+while read -r pkgdir; do
+    echo "=> Checking pkgbase \`$pkgdir'"
+    echo "==> Parsing .SRCINFO"
+    parse_srcinfo "$PKGDIR/$pkgdir" > "$pkgdir.depends"
+    cut -f1 "$pkgdir.depends" > "$pkgdir"
+    echo "==> Checking if new or updated"
+    cut -f1 db_info | comm -13 - "$pkgdir" > "$pkgdir.new"
+    comm -13 aurupdate.pkgname "$pkgdir" > "$pkgdir.update"
 
-if [ -f pkgord ]; then
-    uniq pkgord | sed 's/^\(.*\)$/\.\/aur-src\/\1/' > queue
+    if [ -s "$pkgdir.new" ] || [ -s "$pkgdir.update" ]; then
+        echo "==> Added \`$pkgdir' to build queue"
+        if ! aur depends -n "$pkgdir" 2> /dev/null >> pkgord; then
+            # pkgdir is a group of pkgs
+            echo "$pkgdir" >> pkgord
+        fi
+    fi
+done < pkgdirs
+
+if [ -s pkgord ]; then
+    uniq_unsorted pkgord | sed "s|^\(.*\)$|$PKGDIR\/\1|" > queue
 fi
 
 popd
 
 if [ -s "$tmp/queue" ]; then
-    echo "Building packages"
-    xargs -a "$tmp/queue" -n1 -P1 -I{} echo " - {}"
+    xargs -a "$tmp/queue" -n1 -P1 -I{} echo "=> Building {}"
     aur build -a "$tmp/queue" -c -d "$DB" -s
 else
     echo "Nothing to build"
diff --git a/fetch-aur-pkg b/fetch-aur-pkg
--- a/fetch-aur-pkg
+++ b/fetch-aur-pkg
@@ -1,13 +1,28 @@
 #!/usr/bin/env bash
 
-# this script with patch the given pkg
+## This script uses the aurutils commands. It reads in packages names
+## in a file `PKGLIST` and resolved all AUR dependencies. It then
+## fetchs the repos of all packages (and dependencies), storing them
+## in `PKGDIR`. Finally, the script will look in `PATCHDIR` for any
+## patch files and applies these to the repo(s). Each call of this
+## script resets any existing repos. Additionally, if a packages has
+## been removed from `PKGLIST`, its repo is removed as well.
 
-readonly PKGLIST="$HOME/aur-pkgs-list"
-readonly PKGDIR="$HOME/aur-src"
-readonly PATCHDIR="$HOME/aur-src-patches"
+## More details about patching:
+##  All AUR repos are of the form `<reponame>/PKGBUILD`, if you want
+##  to patch `<reponame>/PKGBUILD`, you create in the `PATCHDIR` the same
+##  directory structure: `$PATCHDIR/<reponame>`, every file you want to
+##  should be of the form `<filename+extenstion>.patch`, e.g.
+##  `PKGBUILD.patch`. Patches are applied on each call of this script.
 
-if [ ! -f "$PKGLIST" ]; then
-	echo "Can't find pkg list, create ${CONF} first before running!" >&2
+readonly ROOTDIR="$HOME"
+
+readonly PKGLIST="$ROOTDIR/aur-pkgs-list"
+readonly PKGDIR="$ROOTDIR/aur-src"
+readonly PATCHDIR="$ROOTDIR/aur-src-patches"
+
+if [ ! -s "$PKGLIST" ]; then
+	echo "Can't find pkg list, create \`${PKGLIST##*/}\` first before running!" >&2
 	exit 1
 else
 	# make sure pkg source dir exists
@@ -29,12 +44,15 @@ else
 	# we want to always reset (so that patch apply cleanly)
 	find . -mindepth 1 -maxdepth 1 -type d -exec git -C {} reset -q --hard master \;
 	xargs -a "$tmp/pkglist" -n1 -P4 aur fetch -g
+    echo "Pruning defunted repos... "
+    find . -mindepth 1 -maxdepth 1 -type d \( $(printf -- "-path */%s -o " $(cat "$tmp/pkglist")) -false \) -prune -o -type d -printf "%P\n" > "$tmp/prune"
+    xargs -a "$tmp/prune" -n1 -P1 rm -rf
 	popd
 
-	echo "Checking for patchs... "
+	echo "Checking for patches... "
 	while read -r pkg; do
 		if [ -d "${PATCHDIR}/${pkg}" ]; then
-			echo "   found, patching $pkg"
+			echo "   found patch, patching $pkg"
 			find "${PATCHDIR}/${pkg}" -iname '*.patch' -exec patch -d "$PKGDIR/$pkg" -p1 -i {} \;
 		fi
 	done < "$PKGLIST"
